name: Automated Tagging
on:
  push:
    branches:
      - main

jobs:
  tag:
    environment:
      name: "prod"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "main"
          token: ${{ secrets.GH_TOKEN }}

      - run: echo "PACKAGE_JSON=$(jq -c . < package.json)" >> $GITHUB_ENV
      - id: generate_tag
        run: echo 'TAG=${{ fromJson(env.PACKAGE_JSON).version }}' >> $GITHUB_OUTPUT

      - name: Create Tag
        run: |
          TAG="${{ steps.generate_tag.outputs.TAG }}"
          git config --local user.email "${{ secrets.GH_EMAIL }}"
          git config --local user.name "${{ secrets.GH_USER }}"
          git tag -a "v$TAG" -m "Release v$TAG"
          git push origin "v$TAG"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: "v${{ steps.generate_tag.outputs.TAG }}"
          release_name: "Release v${{ steps.generate_tag.outputs.TAG }}"
          body: "Last prod updates/features"
